# Generated by Django 4.1.1 on 2022-12-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game", models.CharField(blank=True, max_length=50)),
                ("gameStart", models.IntegerField(default=0)),
                ("round", models.IntegerField(default=0)),
                ("player_to_bet_id", models.IntegerField(null=True)),
                ("community_card", models.CharField(default="", max_length=15)),
                ("dealer_id", models.IntegerField(null=True)),
                ("small_blind_id", models.IntegerField(null=True)),
                ("big_blind_id", models.IntegerField(null=True)),
                ("highest_bet", models.IntegerField(default=0)),
                ("pot", models.IntegerField(default=0)),
                ("won", models.BooleanField(default=False)),
                ("players_ready", models.IntegerField(default=0)),
                ("winner_id", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.IntegerField()),
                ("status", models.IntegerField(default=0)),
                ("role", models.IntegerField(default=-1)),
                ("cards_holding", models.CharField(default="", max_length=10)),
                ("chips", models.IntegerField(default=100)),
                ("bet", models.IntegerField(default=0)),
                ("last_choice", models.CharField(default="not", max_length=10)),
                ("buttons", models.IntegerField(default=0)),
                ("allin", models.BooleanField(default=False)),
                ("folded", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="texas.room"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(blank=True, upload_to="")),
                ("rank", models.IntegerField()),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("tokens", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
